// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input v77ba10,
 output [6:0] va69865,
 output [6:0] vd60617
);
 wire [0:3] w0;
 wire [0:6] w1;
 wire [0:6] w2;
 wire [0:6] w3;
 wire [0:3] w4;
 wire w5;
 wire [0:3] w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire [0:3] w18;
 wire w19;
 assign va69865 = w1;
 assign vd60617 = w2;
 assign w16 = v77ba10;
 assign w18 = w0;
 assign w19 = w5;
 v73ebc2 v0abd6e (
  .vb5e893(w1),
  .v240e0a(w18)
 );
 v9f4f43 v41be9a (
  .vc806bf(w0),
  .vd0d8c2(w4)
 );
 vc4f23a vfcc2f6 (
  .v985fcb(w0),
  .v4f1fd3(w12),
  .vda577d(w13),
  .v3f8943(w14),
  .v64d863(w15)
 );
 vd46be5 v38d0a1 (
  .vcbab45(w5),
  .v0e28cb(w7),
  .v141a59(w8),
  .v1b1eae(w10),
  .v3ca442(w11)
 );
 vcf063d vd16e90 (
  .vcbfa91(w2),
  .va50957(w3)
 );
 v73ebc2 vf78778 (
  .vb5e893(w3),
  .v240e0a(w6)
 );
 ve55f9a v394786 (
  .v999b81(w4),
  .v6dda25(w17),
  .ve556f1(w19)
 );
 v3676a0 vead516 (
  .v0e28cb(w5),
  .vcbab45(w9)
 );
 v98e34e v12988a (
  .v39ec23(w6),
  .v6dda25(w9)
 );
 v3676a0 v52c65c (
  .vcbab45(w7),
  .v0e28cb(w12)
 );
 v3676a0 v070400 (
  .vcbab45(w11),
  .v0e28cb(w13)
 );
 v3676a0 v7f91f2 (
  .vcbab45(w10),
  .v0e28cb(w14)
 );
 v3676a0 v2a9787 (
  .vcbab45(w8),
  .v0e28cb(w15)
 );
 vc71757 v611ec6 (
  .v0daa9e(w16),
  .v2efea4(w17)
 );
endmodule

//---- Top entity
module v73ebc2 (
 input [3:0] v240e0a,
 output [6:0] vb5e893
);
 wire [0:6] w0;
 wire [0:3] w1;
 assign vb5e893 = w0;
 assign w1 = v240e0a;
 v73ebc2_v056811 v056811 (
  .o(w0),
  .i(w1)
 );
endmodule

//---------------------------------------------------
//-- DisplayDEC
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DisplayDEC. Decodificador BCD a 7 segmentos. Ánodo común
//---------------------------------------------------

module v73ebc2_v056811 (
 input [3:0] i,
 output [6:0] o
);
 reg o;
 
 always @(*) 
 begin
 	case(i)
       4'h0: o = 7'b000_0001;
       4'h1: o = 7'b100_1111;
       4'h2: o = 7'b001_0010;
       4'h3: o = 7'b000_0110;
       4'h4: o = 7'b100_1100;
       4'h5: o = 7'b010_0100;
       4'h6: o = 7'b010_0000;
       4'h7: o = 7'b000_1111;
       4'h8: o = 7'b000_0000;
       4'h9: o = 7'b000_0100;
       default: o = 7'b111_1111;
 	endcase
 end
 
endmodule
//---- Top entity
module v9f4f43 (
 input [3:0] vd0d8c2,
 output [3:0] vc806bf
);
 wire [0:3] w0;
 wire [0:3] w1;
 assign w0 = vd0d8c2;
 assign vc806bf = w1;
 v9f4f43_v668229 v668229 (
  .i(w0),
  .o(w1)
 );
endmodule

//---------------------------------------------------
//-- not-x4-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- not-x4-verilog: 4-bits not gate. Verilog implementation
//---------------------------------------------------

module v9f4f43_v668229 (
 input [3:0] i,
 output [3:0] o
);
 //-- Not Gate
 assign o =  ~i;
endmodule
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Split-all: Split the 4-bits bus into its wires
//---------------------------------------------------

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module vd46be5 (
 input v0e28cb,
 input v3ca442,
 input v1b1eae,
 input v141a59,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign w2 = v1b1eae;
 assign vcbab45 = w3;
 assign w4 = v141a59;
 vd46be5_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2),
  .o(w3),
  .d(w4)
 );
endmodule

//---------------------------------------------------
//-- AND4-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AND4-verilog. 4-bits input And gate. Verilog implementation
//---------------------------------------------------

module vd46be5_vf4938a (
 input a,
 input b,
 input c,
 input d,
 output o
);
 //-- AND gate
 //-- Verilog implementation
 
 assign o = a & b & c & d;
 
endmodule
//---- Top entity
module vcf063d (
 input [6:0] va50957,
 output [6:0] vcbfa91
);
 wire [0:6] w0;
 wire [0:6] w1;
 assign w0 = va50957;
 assign vcbfa91 = w1;
 vcf063d_v668229 v668229 (
  .i(w0),
  .o(w1)
 );
endmodule

//---------------------------------------------------
//-- not-x7-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- not-x7-verilog: 7-bits not gate. Verilog implementation
//---------------------------------------------------

module vcf063d_v668229 (
 input [6:0] i,
 output [6:0] o
);
 //-- Not Gate
 assign o =  ~i;
endmodule
//---- Top entity
module ve55f9a (
 input v6dda25,
 input ve556f1,
 output [3:0] v999b81,
 output ve37344
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire w3;
 wire [0:3] w4;
 wire w5;
 assign w0 = ve556f1;
 assign w3 = v6dda25;
 assign v999b81 = w4;
 assign ve37344 = w5;
 assign w4 = w1;
 v778641 vbe6b5c (
  .v782748(w0),
  .v50034e(w1),
  .v4de61b(w2),
  .v6dda25(w3)
 );
 v2a8316 v56200f (
  .v22f91a(w1),
  .ved9156(w2),
  .v4642b6(w5)
 );
endmodule

//---------------------------------------------------
//-- syscounter-rst-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 4-bits Syscounter with reset
//---------------------------------------------------
//---- Top entity
module v778641 (
 input v6dda25,
 input v782748,
 input [3:0] v4de61b,
 output [3:0] v50034e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 assign w6 = v4de61b;
 assign v50034e = w7;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w14 = v782748;
 assign w15 = v782748;
 assign w16 = v782748;
 assign w17 = v782748;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 assign w15 = w14;
 assign w16 = w14;
 assign w16 = w15;
 assign w17 = w14;
 assign w17 = w15;
 assign w17 = w16;
 v869d9b v148526 (
  .v4642b6(w1),
  .vf354ee(w2),
  .vd53b77(w12),
  .v27dec4(w16)
 );
 v869d9b v91d888 (
  .vf354ee(w4),
  .v4642b6(w5),
  .vd53b77(w11),
  .v27dec4(w15)
 );
 vc4f23a v4b1225 (
  .v3f8943(w2),
  .v64d863(w3),
  .vda577d(w4),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v6491fd (
  .v03aaf0(w0),
  .vee8a83(w1),
  .vf8041d(w5),
  .v11bca5(w7),
  .vd84a57(w9)
 );
 vc51332 v418d74 (
  .vf354ee(w8),
  .v4642b6(w9),
  .vd53b77(w10),
  .v27dec4(w14)
 );
 vc51332 v7a72fc (
  .v4642b6(w0),
  .vf354ee(w3),
  .vd53b77(w13),
  .v27dec4(w17)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x04: Three D flip-flops in paralell with reset
//---------------------------------------------------
//---- Top entity
module v869d9b (
 input vd53b77,
 input v27dec4,
 input vf354ee,
 output v4642b6
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign w1 = v27dec4;
 assign w2 = vf354ee;
 assign v4642b6 = w3;
 assign w6 = v27dec4;
 assign w7 = vd53b77;
 assign w6 = w1;
 vc8cfba vae755a (
  .ve8318d(w3),
  .vf54559(w5),
  .va4102a(w7)
 );
 v3676a0 v7539bf (
  .vcbab45(w0),
  .v0e28cb(w1)
 );
 vba518e vfe8158 (
  .v0e28cb(w0),
  .v3ca442(w2),
  .vcbab45(w4)
 );
 v873425 v055c96 (
  .v0e28cb(w4),
  .vcbab45(w5),
  .v3ca442(w6)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x01: D Flip flop with reset input. When rst=1, the DFF is 0
//---------------------------------------------------
//---- Top entity
module vc8cfba #(
 parameter v71e305 = 1
) (
 input va4102a,
 input vf54559,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 vc8cfba_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- DFF
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- D Flip-flop (verilog implementation)
//---------------------------------------------------

module vc8cfba_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg q = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   q <= d;
endmodule
//---- Top entity
module v3676a0 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v3676a0_vd54ca1 vd54ca1 (
  .a(w0),
  .q(w1)
 );
endmodule

//---------------------------------------------------
//-- NOT
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- NOT gate (Verilog implementation)
//---------------------------------------------------

module v3676a0_vd54ca1 (
 input a,
 output q
);
 //-- NOT Gate
 assign q = ~a;
 
 
endmodule
//---- Top entity
module vba518e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vba518e_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- AND2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Two bits input And gate
//---------------------------------------------------

module vba518e_vf4938a (
 input a,
 input b,
 output c
);
 //-- AND gate
 //-- Verilog implementation
 
 assign c = a & b;
 
endmodule
//---- Top entity
module v873425 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v873425_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- OR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- OR2: Two bits input OR gate
//---------------------------------------------------

module v873425_vf4938a (
 input a,
 input b,
 output c
);
 //-- OR Gate
 //-- Verilog implementation
 
 assign c = a | b;
 
 
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Join-all: Join all the wires into a 4-bits Bus
//---------------------------------------------------

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule
//---- Top entity
module vc51332 #(
 parameter vbd3217 = 0
) (
 input vd53b77,
 input v27dec4,
 input vf354ee,
 output v4642b6
);
 localparam p5 = vbd3217;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 assign w2 = v27dec4;
 assign w3 = vf354ee;
 assign v4642b6 = w4;
 assign w6 = vd53b77;
 vc8cfba #(
  .v71e305(p5)
 ) vae755a (
  .vf54559(w0),
  .ve8318d(w4),
  .va4102a(w6)
 );
 v3676a0 v7539bf (
  .vcbab45(w1),
  .v0e28cb(w2)
 );
 vba518e vfe8158 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w3)
 );
endmodule

//---------------------------------------------------
//-- DFF-rst-x01
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-rst-x01: D Flip flop with reset input. When rst=1, the DFF is 0
//---------------------------------------------------
//---- Top entity
module v2a8316 #(
 parameter v6c5139 = 1
) (
 input [3:0] v22f91a,
 output v4642b6,
 output [3:0] ved9156
);
 localparam p1 = v6c5139;
 wire w0;
 wire [0:3] w2;
 wire [0:3] w3;
 assign v4642b6 = w0;
 assign ved9156 = w2;
 assign w3 = v22f91a;
 vc76797 #(
  .vd73390(p1)
 ) vafbab8 (
  .v4642b6(w0),
  .va2f0fe(w2),
  .va9005f(w3)
 );
endmodule

//---------------------------------------------------
//-- Inc1-4bits CLONE
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Inc1-4bit: Increment a 4-bits number by one
//---------------------------------------------------
//---- Top entity
module vc76797 #(
 parameter vd73390 = 0
) (
 input [3:0] va9005f,
 output v4642b6,
 output [3:0] va2f0fe
);
 localparam p1 = vd73390;
 wire w0;
 wire [0:3] w2;
 wire [0:3] w3;
 wire [0:3] w4;
 assign v4642b6 = w0;
 assign w2 = va9005f;
 assign va2f0fe = w4;
 v9b9118 #(
  .vc5c8ea(p1)
 ) v5a7625 (
  .v1ef182(w3)
 );
 v25966b v51fafd (
  .v4642b6(w0),
  .v24708e(w2),
  .v0550b6(w3),
  .v817794(w4)
 );
endmodule

//---------------------------------------------------
//-- AdderK-4bits CLONE CLONE
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderK-4bit: Adder of 4-bit operand and 4-bit constant
//---------------------------------------------------
//---- Top entity
module v9b9118 #(
 parameter vc5c8ea = 0
) (
 output [3:0] v1ef182
);
 localparam p0 = vc5c8ea;
 wire [0:3] w1;
 assign v1ef182 = w1;
 v9b9118_v465065 #(
  .VALUE(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

//---------------------------------------------------
//-- 4-bits-gen-constant
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Generic: 4-bits generic constant (0-15)
//---------------------------------------------------

module v9b9118_v465065 #(
 parameter VALUE = 0
) (
 output [3:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module v25966b (
 input [3:0] v0550b6,
 input [3:0] v24708e,
 output v4642b6,
 output [3:0] v817794
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 assign w5 = v24708e;
 assign w6 = v0550b6;
 assign v817794 = w7;
 assign v4642b6 = w9;
 v1ea21d vdbe125 (
  .v4642b6(w0),
  .v8e8a67(w2),
  .v27dec4(w15),
  .v82de4f(w18)
 );
 vad119b vb8ad86 (
  .v0ef266(w0),
  .v8e8a67(w1),
  .v4642b6(w3),
  .v27dec4(w14),
  .v82de4f(w17)
 );
 vad119b v5d29b2 (
  .v0ef266(w3),
  .v8e8a67(w4),
  .v4642b6(w8),
  .v27dec4(w12),
  .v82de4f(w16)
 );
 vc4f23a vf4a6ff (
  .v985fcb(w5),
  .v4f1fd3(w13),
  .vda577d(w16),
  .v3f8943(w17),
  .v64d863(w18)
 );
 vc4f23a v9d4632 (
  .v985fcb(w6),
  .v4f1fd3(w11),
  .vda577d(w12),
  .v3f8943(w14),
  .v64d863(w15)
 );
 v84f0a1 v140dbf (
  .vee8a83(w1),
  .v03aaf0(w2),
  .vf8041d(w4),
  .v11bca5(w7),
  .vd84a57(w10)
 );
 vad119b v5c5937 (
  .v0ef266(w8),
  .v4642b6(w9),
  .v8e8a67(w10),
  .v27dec4(w11),
  .v82de4f(w13)
 );
endmodule

//---------------------------------------------------
//-- Adder-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-4bits: Adder of two operands of 4 bits
//---------------------------------------------------
//---- Top entity
module v1ea21d (
 input v27dec4,
 input v82de4f,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v82de4f;
 assign w1 = v27dec4;
 assign v4642b6 = w3;
 assign v8e8a67 = w4;
 vad119b vb820a1 (
  .v82de4f(w0),
  .v27dec4(w1),
  .v0ef266(w2),
  .v4642b6(w3),
  .v8e8a67(w4)
 );
 vd30ca9 v23ebb6 (
  .v9fb85f(w2)
 );
endmodule

//---------------------------------------------------
//-- Adder-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Adder-1bit: Adder of two operands of 1 bit
//---------------------------------------------------
//---- Top entity
module vad119b (
 input v27dec4,
 input v82de4f,
 input v0ef266,
 output v4642b6,
 output v8e8a67
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v8e8a67 = w1;
 assign v4642b6 = w5;
 assign w6 = v27dec4;
 assign w7 = v27dec4;
 assign w8 = v82de4f;
 assign w9 = v82de4f;
 assign w10 = v0ef266;
 assign w11 = v0ef266;
 assign w2 = w0;
 assign w7 = w6;
 assign w9 = w8;
 assign w11 = w10;
 vd12401 v2e3d9f (
  .vcbab45(w0),
  .v0e28cb(w7),
  .v3ca442(w9)
 );
 vd12401 vb50462 (
  .v0e28cb(w0),
  .vcbab45(w1),
  .v3ca442(w11)
 );
 vba518e v4882f4 (
  .v3ca442(w2),
  .vcbab45(w3),
  .v0e28cb(w10)
 );
 vba518e v8fcf41 (
  .vcbab45(w4),
  .v0e28cb(w6),
  .v3ca442(w8)
 );
 v873425 vc5b8b9 (
  .v3ca442(w3),
  .v0e28cb(w4),
  .vcbab45(w5)
 );
endmodule

//---------------------------------------------------
//-- AdderC-1bit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- AdderC-1bit: Adder of two operands of 1 bit plus the carry in
//---------------------------------------------------
//---- Top entity
module vd12401 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vd12401_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

//---------------------------------------------------
//-- XOR2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- XOR gate: two bits input xor gate
//---------------------------------------------------

module vd12401_vf4938a (
 input a,
 input b,
 output c
);
 //-- XOR gate
 //-- Verilog implementation
 
 assign c = a ^ b;
 
endmodule
//---- Top entity
module vd30ca9 (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 vd30ca9_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

//---------------------------------------------------
//-- bit-0
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Constant bit 0
//---------------------------------------------------

module vd30ca9_vb2eccd (
 output q
);
 //-- Constant bit-0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v98e34e (
 input v6dda25,
 output [3:0] v39ec23,
 output ve37344
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire w2;
 wire [0:3] w3;
 wire w4;
 assign w2 = v6dda25;
 assign v39ec23 = w3;
 assign ve37344 = w4;
 assign w3 = w0;
 vbd8fcb v9ea4bb (
  .vf6ad19(w0),
  .v7c67e1(w1),
  .v6dda25(w2)
 );
 v2a8316 vd4523e (
  .v22f91a(w0),
  .ved9156(w1),
  .v4642b6(w4)
 );
endmodule

//---------------------------------------------------
//-- syscounter-4bits
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 4-bits Syscounter
//---------------------------------------------------
//---- Top entity
module vbd8fcb (
 input v6dda25,
 input [3:0] v7c67e1,
 output [3:0] vf6ad19
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire w12;
 wire w13;
 assign w4 = v7c67e1;
 assign vf6ad19 = w5;
 assign w10 = v6dda25;
 assign w11 = v6dda25;
 assign w12 = v6dda25;
 assign w13 = v6dda25;
 assign w8 = w7;
 assign w9 = w7;
 assign w9 = w8;
 assign w11 = w10;
 assign w12 = w10;
 assign w12 = w11;
 assign w13 = w10;
 assign w13 = w11;
 assign w13 = w12;
 vc8cfba v5da2d5 (
  .vf54559(w0),
  .va4102a(w12)
 );
 vc8cfba v78b38a (
  .vf54559(w1),
  .ve8318d(w2),
  .va4102a(w13)
 );
 vc8cfba v14ff4d (
  .vf54559(w3),
  .va4102a(w11)
 );
 vc4f23a v390ed9 (
  .v3f8943(w0),
  .v64d863(w1),
  .vda577d(w3),
  .v985fcb(w4),
  .v4f1fd3(w6)
 );
 v84f0a1 v0e8f25 (
  .v03aaf0(w2),
  .v11bca5(w5),
  .vee8a83(w7),
  .vf8041d(w8),
  .vd84a57(w9)
 );
 vc8cfba vddbb2a (
  .vf54559(w6),
  .va4102a(w10)
 );
 vd30ca9 vba04c6 (
  .v9fb85f(w7)
 );
endmodule

//---------------------------------------------------
//-- DFF-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DFF-04: Three D flip-flops in paralell
//---------------------------------------------------
//---- Top entity
module vc71757 #(
 parameter v245bef = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p1 = v245bef;
 wire w0;
 wire w2;
 assign w0 = v0daa9e;
 assign v2efea4 = w2;
 v435b29 #(
  .v100e1b(p1)
 ) v81886f (
  .v0daa9e(w0),
  .v2efea4(w2)
 );
endmodule

//---------------------------------------------------
//-- Prescaler22
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 22-bits prescaler
//---------------------------------------------------
//---- Top entity
module v435b29 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v435b29_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v435b29_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
